// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/lssdrpc.proto

package lssdrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OrderSide int32

const (
	OrderSide_buy  OrderSide = 0
	OrderSide_sell OrderSide = 1
)

var OrderSide_name = map[int32]string{
	0: "buy",
	1: "sell",
}

var OrderSide_value = map[string]int32{
	"buy":  0,
	"sell": 1,
}

func (x OrderSide) String() string {
	return proto.EnumName(OrderSide_name, int32(x))
}

func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{0}
}

type SwapSuccess_Role int32

const (
	SwapSuccess_TAKER SwapSuccess_Role = 0
	SwapSuccess_MAKER SwapSuccess_Role = 1
)

var SwapSuccess_Role_name = map[int32]string{
	0: "TAKER",
	1: "MAKER",
}

var SwapSuccess_Role_value = map[string]int32{
	"TAKER": 0,
	"MAKER": 1,
}

func (x SwapSuccess_Role) String() string {
	return proto.EnumName(SwapSuccess_Role_name, int32(x))
}

func (SwapSuccess_Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{18, 0}
}

// A non-negative Big Integer represented as string, like "100000000"
type BigInteger struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigInteger) Reset()         { *m = BigInteger{} }
func (m *BigInteger) String() string { return proto.CompactTextString(m) }
func (*BigInteger) ProtoMessage()    {}
func (*BigInteger) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{0}
}

func (m *BigInteger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigInteger.Unmarshal(m, b)
}
func (m *BigInteger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigInteger.Marshal(b, m, deterministic)
}
func (m *BigInteger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigInteger.Merge(m, src)
}
func (m *BigInteger) XXX_Size() int {
	return xxx_messageInfo_BigInteger.Size(m)
}
func (m *BigInteger) XXX_DiscardUnknown() {
	xxx_messageInfo_BigInteger.DiscardUnknown(m)
}

var xxx_messageInfo_BigInteger proto.InternalMessageInfo

func (m *BigInteger) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AddCurrencyRequest struct {
	// the currency, like XSN or LTC
	Currency string `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	// the address:port allowing lssd to connect to this currency lnd, like "localhost:10001"
	// right now, it is assumed that the bot runs on the same network than lssd, so, there is
	// no support for authentication.
	LndChannel string `protobuf:"bytes,2,opt,name=lndChannel,proto3" json:"lndChannel,omitempty"`
	// the tls certificate used by lnd, so that lssd can be sure it's connecting to the right lnd
	//
	// Types that are valid to be assigned to TlsCert:
	//	*AddCurrencyRequest_CertPath
	//	*AddCurrencyRequest_RawCert
	TlsCert              isAddCurrencyRequest_TlsCert `protobuf_oneof:"tlsCert"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *AddCurrencyRequest) Reset()         { *m = AddCurrencyRequest{} }
func (m *AddCurrencyRequest) String() string { return proto.CompactTextString(m) }
func (*AddCurrencyRequest) ProtoMessage()    {}
func (*AddCurrencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{1}
}

func (m *AddCurrencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCurrencyRequest.Unmarshal(m, b)
}
func (m *AddCurrencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCurrencyRequest.Marshal(b, m, deterministic)
}
func (m *AddCurrencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCurrencyRequest.Merge(m, src)
}
func (m *AddCurrencyRequest) XXX_Size() int {
	return xxx_messageInfo_AddCurrencyRequest.Size(m)
}
func (m *AddCurrencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCurrencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCurrencyRequest proto.InternalMessageInfo

func (m *AddCurrencyRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *AddCurrencyRequest) GetLndChannel() string {
	if m != nil {
		return m.LndChannel
	}
	return ""
}

type isAddCurrencyRequest_TlsCert interface {
	isAddCurrencyRequest_TlsCert()
}

type AddCurrencyRequest_CertPath struct {
	CertPath string `protobuf:"bytes,3,opt,name=certPath,proto3,oneof"`
}

type AddCurrencyRequest_RawCert struct {
	RawCert string `protobuf:"bytes,4,opt,name=rawCert,proto3,oneof"`
}

func (*AddCurrencyRequest_CertPath) isAddCurrencyRequest_TlsCert() {}

func (*AddCurrencyRequest_RawCert) isAddCurrencyRequest_TlsCert() {}

func (m *AddCurrencyRequest) GetTlsCert() isAddCurrencyRequest_TlsCert {
	if m != nil {
		return m.TlsCert
	}
	return nil
}

func (m *AddCurrencyRequest) GetCertPath() string {
	if x, ok := m.GetTlsCert().(*AddCurrencyRequest_CertPath); ok {
		return x.CertPath
	}
	return ""
}

func (m *AddCurrencyRequest) GetRawCert() string {
	if x, ok := m.GetTlsCert().(*AddCurrencyRequest_RawCert); ok {
		return x.RawCert
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AddCurrencyRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AddCurrencyRequest_CertPath)(nil),
		(*AddCurrencyRequest_RawCert)(nil),
	}
}

type AddCurrencyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCurrencyResponse) Reset()         { *m = AddCurrencyResponse{} }
func (m *AddCurrencyResponse) String() string { return proto.CompactTextString(m) }
func (*AddCurrencyResponse) ProtoMessage()    {}
func (*AddCurrencyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{2}
}

func (m *AddCurrencyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCurrencyResponse.Unmarshal(m, b)
}
func (m *AddCurrencyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCurrencyResponse.Marshal(b, m, deterministic)
}
func (m *AddCurrencyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCurrencyResponse.Merge(m, src)
}
func (m *AddCurrencyResponse) XXX_Size() int {
	return xxx_messageInfo_AddCurrencyResponse.Size(m)
}
func (m *AddCurrencyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCurrencyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCurrencyResponse proto.InternalMessageInfo

type EnableTradingPairRequest struct {
	PairId               string   `protobuf:"bytes,1,opt,name=pairId,proto3" json:"pairId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableTradingPairRequest) Reset()         { *m = EnableTradingPairRequest{} }
func (m *EnableTradingPairRequest) String() string { return proto.CompactTextString(m) }
func (*EnableTradingPairRequest) ProtoMessage()    {}
func (*EnableTradingPairRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{3}
}

func (m *EnableTradingPairRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableTradingPairRequest.Unmarshal(m, b)
}
func (m *EnableTradingPairRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableTradingPairRequest.Marshal(b, m, deterministic)
}
func (m *EnableTradingPairRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableTradingPairRequest.Merge(m, src)
}
func (m *EnableTradingPairRequest) XXX_Size() int {
	return xxx_messageInfo_EnableTradingPairRequest.Size(m)
}
func (m *EnableTradingPairRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableTradingPairRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableTradingPairRequest proto.InternalMessageInfo

func (m *EnableTradingPairRequest) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

type EnableTradingPairResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableTradingPairResponse) Reset()         { *m = EnableTradingPairResponse{} }
func (m *EnableTradingPairResponse) String() string { return proto.CompactTextString(m) }
func (*EnableTradingPairResponse) ProtoMessage()    {}
func (*EnableTradingPairResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{4}
}

func (m *EnableTradingPairResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableTradingPairResponse.Unmarshal(m, b)
}
func (m *EnableTradingPairResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableTradingPairResponse.Marshal(b, m, deterministic)
}
func (m *EnableTradingPairResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableTradingPairResponse.Merge(m, src)
}
func (m *EnableTradingPairResponse) XXX_Size() int {
	return xxx_messageInfo_EnableTradingPairResponse.Size(m)
}
func (m *EnableTradingPairResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableTradingPairResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnableTradingPairResponse proto.InternalMessageInfo

type ListOrdersRequest struct {
	PairId               string   `protobuf:"bytes,1,opt,name=pairId,proto3" json:"pairId,omitempty"`
	IncludeOwnOrders     bool     `protobuf:"varint,2,opt,name=includeOwnOrders,proto3" json:"includeOwnOrders,omitempty"`
	Skip                 uint32   `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                uint32   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrdersRequest) Reset()         { *m = ListOrdersRequest{} }
func (m *ListOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*ListOrdersRequest) ProtoMessage()    {}
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{5}
}

func (m *ListOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrdersRequest.Unmarshal(m, b)
}
func (m *ListOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrdersRequest.Marshal(b, m, deterministic)
}
func (m *ListOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrdersRequest.Merge(m, src)
}
func (m *ListOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_ListOrdersRequest.Size(m)
}
func (m *ListOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrdersRequest proto.InternalMessageInfo

func (m *ListOrdersRequest) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *ListOrdersRequest) GetIncludeOwnOrders() bool {
	if m != nil {
		return m.IncludeOwnOrders
	}
	return false
}

func (m *ListOrdersRequest) GetSkip() uint32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *ListOrdersRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListOrdersResponse struct {
	Orders               []*Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrdersResponse) Reset()         { *m = ListOrdersResponse{} }
func (m *ListOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*ListOrdersResponse) ProtoMessage()    {}
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{6}
}

func (m *ListOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrdersResponse.Unmarshal(m, b)
}
func (m *ListOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrdersResponse.Marshal(b, m, deterministic)
}
func (m *ListOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrdersResponse.Merge(m, src)
}
func (m *ListOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_ListOrdersResponse.Size(m)
}
func (m *ListOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrdersResponse proto.InternalMessageInfo

func (m *ListOrdersResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type PlaceOrderRequest struct {
	PairId               string      `protobuf:"bytes,1,opt,name=pairId,proto3" json:"pairId,omitempty"`
	Side                 OrderSide   `protobuf:"varint,2,opt,name=side,proto3,enum=lssdrpc.OrderSide" json:"side,omitempty"`
	Funds                *BigInteger `protobuf:"bytes,3,opt,name=funds,proto3" json:"funds,omitempty"`
	Price                *BigInteger `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlaceOrderRequest) Reset()         { *m = PlaceOrderRequest{} }
func (m *PlaceOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderRequest) ProtoMessage()    {}
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{7}
}

func (m *PlaceOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderRequest.Unmarshal(m, b)
}
func (m *PlaceOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderRequest.Marshal(b, m, deterministic)
}
func (m *PlaceOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderRequest.Merge(m, src)
}
func (m *PlaceOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderRequest.Size(m)
}
func (m *PlaceOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderRequest proto.InternalMessageInfo

func (m *PlaceOrderRequest) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *PlaceOrderRequest) GetSide() OrderSide {
	if m != nil {
		return m.Side
	}
	return OrderSide_buy
}

func (m *PlaceOrderRequest) GetFunds() *BigInteger {
	if m != nil {
		return m.Funds
	}
	return nil
}

func (m *PlaceOrderRequest) GetPrice() *BigInteger {
	if m != nil {
		return m.Price
	}
	return nil
}

// Outcome of place order, three possible situations
// 1. Order was placed
// 2. Order was placed and matched without going to orderbook
// 3. Place order or swap has failed
type PlaceOrderResponse struct {
	// Types that are valid to be assigned to Outcome:
	//	*PlaceOrderResponse_SwapSuccess
	//	*PlaceOrderResponse_Order
	//	*PlaceOrderResponse_Failure
	Outcome              isPlaceOrderResponse_Outcome `protobuf_oneof:"outcome"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *PlaceOrderResponse) Reset()         { *m = PlaceOrderResponse{} }
func (m *PlaceOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderResponse) ProtoMessage()    {}
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{8}
}

func (m *PlaceOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderResponse.Unmarshal(m, b)
}
func (m *PlaceOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderResponse.Marshal(b, m, deterministic)
}
func (m *PlaceOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderResponse.Merge(m, src)
}
func (m *PlaceOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderResponse.Size(m)
}
func (m *PlaceOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderResponse proto.InternalMessageInfo

type isPlaceOrderResponse_Outcome interface {
	isPlaceOrderResponse_Outcome()
}

type PlaceOrderResponse_SwapSuccess struct {
	SwapSuccess *SwapSuccess `protobuf:"bytes,1,opt,name=swapSuccess,proto3,oneof"`
}

type PlaceOrderResponse_Order struct {
	Order *Order `protobuf:"bytes,2,opt,name=order,proto3,oneof"`
}

type PlaceOrderResponse_Failure struct {
	Failure *PlaceOrderFailure `protobuf:"bytes,3,opt,name=failure,proto3,oneof"`
}

func (*PlaceOrderResponse_SwapSuccess) isPlaceOrderResponse_Outcome() {}

func (*PlaceOrderResponse_Order) isPlaceOrderResponse_Outcome() {}

func (*PlaceOrderResponse_Failure) isPlaceOrderResponse_Outcome() {}

func (m *PlaceOrderResponse) GetOutcome() isPlaceOrderResponse_Outcome {
	if m != nil {
		return m.Outcome
	}
	return nil
}

func (m *PlaceOrderResponse) GetSwapSuccess() *SwapSuccess {
	if x, ok := m.GetOutcome().(*PlaceOrderResponse_SwapSuccess); ok {
		return x.SwapSuccess
	}
	return nil
}

func (m *PlaceOrderResponse) GetOrder() *Order {
	if x, ok := m.GetOutcome().(*PlaceOrderResponse_Order); ok {
		return x.Order
	}
	return nil
}

func (m *PlaceOrderResponse) GetFailure() *PlaceOrderFailure {
	if x, ok := m.GetOutcome().(*PlaceOrderResponse_Failure); ok {
		return x.Failure
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PlaceOrderResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PlaceOrderResponse_SwapSuccess)(nil),
		(*PlaceOrderResponse_Order)(nil),
		(*PlaceOrderResponse_Failure)(nil),
	}
}

type OrderbookFailure struct {
	PairId               string      `protobuf:"bytes,1,opt,name=pairId,proto3" json:"pairId,omitempty"`
	Funds                *BigInteger `protobuf:"bytes,2,opt,name=funds,proto3" json:"funds,omitempty"`
	FailureReason        string      `protobuf:"bytes,3,opt,name=failureReason,proto3" json:"failureReason,omitempty"`
	RequiredFee          *BigInteger `protobuf:"bytes,4,opt,name=requiredFee,proto3" json:"requiredFee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OrderbookFailure) Reset()         { *m = OrderbookFailure{} }
func (m *OrderbookFailure) String() string { return proto.CompactTextString(m) }
func (*OrderbookFailure) ProtoMessage()    {}
func (*OrderbookFailure) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{9}
}

func (m *OrderbookFailure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderbookFailure.Unmarshal(m, b)
}
func (m *OrderbookFailure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderbookFailure.Marshal(b, m, deterministic)
}
func (m *OrderbookFailure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderbookFailure.Merge(m, src)
}
func (m *OrderbookFailure) XXX_Size() int {
	return xxx_messageInfo_OrderbookFailure.Size(m)
}
func (m *OrderbookFailure) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderbookFailure.DiscardUnknown(m)
}

var xxx_messageInfo_OrderbookFailure proto.InternalMessageInfo

func (m *OrderbookFailure) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *OrderbookFailure) GetFunds() *BigInteger {
	if m != nil {
		return m.Funds
	}
	return nil
}

func (m *OrderbookFailure) GetFailureReason() string {
	if m != nil {
		return m.FailureReason
	}
	return ""
}

func (m *OrderbookFailure) GetRequiredFee() *BigInteger {
	if m != nil {
		return m.RequiredFee
	}
	return nil
}

type PlaceOrderFailure struct {
	// Types that are valid to be assigned to Failure:
	//	*PlaceOrderFailure_SwapFailure
	//	*PlaceOrderFailure_OrderbookFalure
	Failure              isPlaceOrderFailure_Failure `protobuf_oneof:"failure"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *PlaceOrderFailure) Reset()         { *m = PlaceOrderFailure{} }
func (m *PlaceOrderFailure) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderFailure) ProtoMessage()    {}
func (*PlaceOrderFailure) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{10}
}

func (m *PlaceOrderFailure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderFailure.Unmarshal(m, b)
}
func (m *PlaceOrderFailure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderFailure.Marshal(b, m, deterministic)
}
func (m *PlaceOrderFailure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderFailure.Merge(m, src)
}
func (m *PlaceOrderFailure) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderFailure.Size(m)
}
func (m *PlaceOrderFailure) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderFailure.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderFailure proto.InternalMessageInfo

type isPlaceOrderFailure_Failure interface {
	isPlaceOrderFailure_Failure()
}

type PlaceOrderFailure_SwapFailure struct {
	SwapFailure *SwapFailure `protobuf:"bytes,1,opt,name=swapFailure,proto3,oneof"`
}

type PlaceOrderFailure_OrderbookFalure struct {
	OrderbookFalure *OrderbookFailure `protobuf:"bytes,2,opt,name=orderbookFalure,proto3,oneof"`
}

func (*PlaceOrderFailure_SwapFailure) isPlaceOrderFailure_Failure() {}

func (*PlaceOrderFailure_OrderbookFalure) isPlaceOrderFailure_Failure() {}

func (m *PlaceOrderFailure) GetFailure() isPlaceOrderFailure_Failure {
	if m != nil {
		return m.Failure
	}
	return nil
}

func (m *PlaceOrderFailure) GetSwapFailure() *SwapFailure {
	if x, ok := m.GetFailure().(*PlaceOrderFailure_SwapFailure); ok {
		return x.SwapFailure
	}
	return nil
}

func (m *PlaceOrderFailure) GetOrderbookFalure() *OrderbookFailure {
	if x, ok := m.GetFailure().(*PlaceOrderFailure_OrderbookFalure); ok {
		return x.OrderbookFalure
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PlaceOrderFailure) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PlaceOrderFailure_SwapFailure)(nil),
		(*PlaceOrderFailure_OrderbookFalure)(nil),
	}
}

type CancelOrderRequest struct {
	PairId               string   `protobuf:"bytes,1,opt,name=pairId,proto3" json:"pairId,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderRequest) Reset()         { *m = CancelOrderRequest{} }
func (m *CancelOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CancelOrderRequest) ProtoMessage()    {}
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{11}
}

func (m *CancelOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderRequest.Unmarshal(m, b)
}
func (m *CancelOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderRequest.Marshal(b, m, deterministic)
}
func (m *CancelOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderRequest.Merge(m, src)
}
func (m *CancelOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CancelOrderRequest.Size(m)
}
func (m *CancelOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderRequest proto.InternalMessageInfo

func (m *CancelOrderRequest) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *CancelOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type CancelOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderResponse) Reset()         { *m = CancelOrderResponse{} }
func (m *CancelOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CancelOrderResponse) ProtoMessage()    {}
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{12}
}

func (m *CancelOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderResponse.Unmarshal(m, b)
}
func (m *CancelOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderResponse.Marshal(b, m, deterministic)
}
func (m *CancelOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderResponse.Merge(m, src)
}
func (m *CancelOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CancelOrderResponse.Size(m)
}
func (m *CancelOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderResponse proto.InternalMessageInfo

type SubscribeOrdersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeOrdersRequest) Reset()         { *m = SubscribeOrdersRequest{} }
func (m *SubscribeOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeOrdersRequest) ProtoMessage()    {}
func (*SubscribeOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{13}
}

func (m *SubscribeOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeOrdersRequest.Unmarshal(m, b)
}
func (m *SubscribeOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeOrdersRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeOrdersRequest.Merge(m, src)
}
func (m *SubscribeOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeOrdersRequest.Size(m)
}
func (m *SubscribeOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeOrdersRequest proto.InternalMessageInfo

type OrderUpdate struct {
	// Types that are valid to be assigned to Update:
	//	*OrderUpdate_Order
	//	*OrderUpdate_OrderRemoval
	Update               isOrderUpdate_Update `protobuf_oneof:"update"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderUpdate) Reset()         { *m = OrderUpdate{} }
func (m *OrderUpdate) String() string { return proto.CompactTextString(m) }
func (*OrderUpdate) ProtoMessage()    {}
func (*OrderUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{14}
}

func (m *OrderUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderUpdate.Unmarshal(m, b)
}
func (m *OrderUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderUpdate.Marshal(b, m, deterministic)
}
func (m *OrderUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderUpdate.Merge(m, src)
}
func (m *OrderUpdate) XXX_Size() int {
	return xxx_messageInfo_OrderUpdate.Size(m)
}
func (m *OrderUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_OrderUpdate proto.InternalMessageInfo

type isOrderUpdate_Update interface {
	isOrderUpdate_Update()
}

type OrderUpdate_Order struct {
	Order *Order `protobuf:"bytes,1,opt,name=order,proto3,oneof"`
}

type OrderUpdate_OrderRemoval struct {
	OrderRemoval *Order `protobuf:"bytes,2,opt,name=orderRemoval,proto3,oneof"`
}

func (*OrderUpdate_Order) isOrderUpdate_Update() {}

func (*OrderUpdate_OrderRemoval) isOrderUpdate_Update() {}

func (m *OrderUpdate) GetUpdate() isOrderUpdate_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *OrderUpdate) GetOrder() *Order {
	if x, ok := m.GetUpdate().(*OrderUpdate_Order); ok {
		return x.Order
	}
	return nil
}

func (m *OrderUpdate) GetOrderRemoval() *Order {
	if x, ok := m.GetUpdate().(*OrderUpdate_OrderRemoval); ok {
		return x.OrderRemoval
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*OrderUpdate) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*OrderUpdate_Order)(nil),
		(*OrderUpdate_OrderRemoval)(nil),
	}
}

type Order struct {
	PairId  string `protobuf:"bytes,1,opt,name=pairId,proto3" json:"pairId,omitempty"`
	OrderId string `protobuf:"bytes,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	// The price of the order in satoshis.
	Price *BigInteger `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	// The funds of the order in satoshis.
	Funds *BigInteger `protobuf:"bytes,4,opt,name=funds,proto3" json:"funds,omitempty"`
	// The epoch time when this order was created.
	CreatedAt uint64 `protobuf:"varint,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// Whether this order is a buy or sell
	Side OrderSide `protobuf:"varint,6,opt,name=side,proto3,enum=lssdrpc.OrderSide" json:"side,omitempty"`
	// Whether this order is a local own order or a remote peer order.
	IsOwnOrder           bool     `protobuf:"varint,7,opt,name=isOwnOrder,proto3" json:"isOwnOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{15}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *Order) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Order) GetPrice() *BigInteger {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *Order) GetFunds() *BigInteger {
	if m != nil {
		return m.Funds
	}
	return nil
}

func (m *Order) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Order) GetSide() OrderSide {
	if m != nil {
		return m.Side
	}
	return OrderSide_buy
}

func (m *Order) GetIsOwnOrder() bool {
	if m != nil {
		return m.IsOwnOrder
	}
	return false
}

type SubscribeSwapsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeSwapsRequest) Reset()         { *m = SubscribeSwapsRequest{} }
func (m *SubscribeSwapsRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeSwapsRequest) ProtoMessage()    {}
func (*SubscribeSwapsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{16}
}

func (m *SubscribeSwapsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeSwapsRequest.Unmarshal(m, b)
}
func (m *SubscribeSwapsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeSwapsRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeSwapsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeSwapsRequest.Merge(m, src)
}
func (m *SubscribeSwapsRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeSwapsRequest.Size(m)
}
func (m *SubscribeSwapsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeSwapsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeSwapsRequest proto.InternalMessageInfo

type SwapResult struct {
	// Types that are valid to be assigned to Value:
	//	*SwapResult_Success
	//	*SwapResult_Failure
	Value                isSwapResult_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SwapResult) Reset()         { *m = SwapResult{} }
func (m *SwapResult) String() string { return proto.CompactTextString(m) }
func (*SwapResult) ProtoMessage()    {}
func (*SwapResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{17}
}

func (m *SwapResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwapResult.Unmarshal(m, b)
}
func (m *SwapResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwapResult.Marshal(b, m, deterministic)
}
func (m *SwapResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapResult.Merge(m, src)
}
func (m *SwapResult) XXX_Size() int {
	return xxx_messageInfo_SwapResult.Size(m)
}
func (m *SwapResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapResult.DiscardUnknown(m)
}

var xxx_messageInfo_SwapResult proto.InternalMessageInfo

type isSwapResult_Value interface {
	isSwapResult_Value()
}

type SwapResult_Success struct {
	Success *SwapSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type SwapResult_Failure struct {
	Failure *SwapFailure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*SwapResult_Success) isSwapResult_Value() {}

func (*SwapResult_Failure) isSwapResult_Value() {}

func (m *SwapResult) GetValue() isSwapResult_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SwapResult) GetSuccess() *SwapSuccess {
	if x, ok := m.GetValue().(*SwapResult_Success); ok {
		return x.Success
	}
	return nil
}

func (m *SwapResult) GetFailure() *SwapFailure {
	if x, ok := m.GetValue().(*SwapResult_Failure); ok {
		return x.Failure
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SwapResult) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SwapResult_Success)(nil),
		(*SwapResult_Failure)(nil),
	}
}

type SwapSuccess struct {
	// Order id assigned by orderbook
	OrderId string `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	// The trading pair that the swap is for.
	PairId string `protobuf:"bytes,2,opt,name=pairId,proto3" json:"pairId,omitempty"`
	// The order funds that was swapped.
	Funds *BigInteger `protobuf:"bytes,3,opt,name=funds,proto3" json:"funds,omitempty"`
	// The hex-encoded payment hash for the swap.
	RHash string `protobuf:"bytes,4,opt,name=rHash,proto3" json:"rHash,omitempty"`
	// The amount received denominated in satoshis.
	AmountReceived *BigInteger `protobuf:"bytes,5,opt,name=amountReceived,proto3" json:"amountReceived,omitempty"`
	// The amount sent denominated in satoshis.
	AmountSent *BigInteger `protobuf:"bytes,6,opt,name=amountSent,proto3" json:"amountSent,omitempty"`
	// Our role in the swap, either MAKER or TAKER.
	Role SwapSuccess_Role `protobuf:"varint,7,opt,name=role,proto3,enum=lssdrpc.SwapSuccess_Role" json:"role,omitempty"`
	// The ticker symbol of the currency received.
	CurrencyReceived string `protobuf:"bytes,8,opt,name=currencyReceived,proto3" json:"currencyReceived,omitempty"`
	// The ticker symbol of the currency sent.
	CurrencySent string `protobuf:"bytes,9,opt,name=currencySent,proto3" json:"currencySent,omitempty"`
	// The hex-encoded preimage.
	RPreimage string `protobuf:"bytes,10,opt,name=rPreimage,proto3" json:"rPreimage,omitempty"`
	// The price used for the swap.
	Price                *BigInteger `protobuf:"bytes,11,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SwapSuccess) Reset()         { *m = SwapSuccess{} }
func (m *SwapSuccess) String() string { return proto.CompactTextString(m) }
func (*SwapSuccess) ProtoMessage()    {}
func (*SwapSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{18}
}

func (m *SwapSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwapSuccess.Unmarshal(m, b)
}
func (m *SwapSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwapSuccess.Marshal(b, m, deterministic)
}
func (m *SwapSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapSuccess.Merge(m, src)
}
func (m *SwapSuccess) XXX_Size() int {
	return xxx_messageInfo_SwapSuccess.Size(m)
}
func (m *SwapSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_SwapSuccess proto.InternalMessageInfo

func (m *SwapSuccess) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *SwapSuccess) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *SwapSuccess) GetFunds() *BigInteger {
	if m != nil {
		return m.Funds
	}
	return nil
}

func (m *SwapSuccess) GetRHash() string {
	if m != nil {
		return m.RHash
	}
	return ""
}

func (m *SwapSuccess) GetAmountReceived() *BigInteger {
	if m != nil {
		return m.AmountReceived
	}
	return nil
}

func (m *SwapSuccess) GetAmountSent() *BigInteger {
	if m != nil {
		return m.AmountSent
	}
	return nil
}

func (m *SwapSuccess) GetRole() SwapSuccess_Role {
	if m != nil {
		return m.Role
	}
	return SwapSuccess_TAKER
}

func (m *SwapSuccess) GetCurrencyReceived() string {
	if m != nil {
		return m.CurrencyReceived
	}
	return ""
}

func (m *SwapSuccess) GetCurrencySent() string {
	if m != nil {
		return m.CurrencySent
	}
	return ""
}

func (m *SwapSuccess) GetRPreimage() string {
	if m != nil {
		return m.RPreimage
	}
	return ""
}

func (m *SwapSuccess) GetPrice() *BigInteger {
	if m != nil {
		return m.Price
	}
	return nil
}

type SwapFailure struct {
	// Order id assigned by orderbook
	OrderId string `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	// The trading pair that the swap is for.
	PairId string `protobuf:"bytes,2,opt,name=pairId,proto3" json:"pairId,omitempty"`
	// The order funds that was attempted to be swapped.
	Funds *BigInteger `protobuf:"bytes,3,opt,name=funds,proto3" json:"funds,omitempty"`
	// The reason why the swap failed.
	FailureReason        string   `protobuf:"bytes,4,opt,name=failureReason,proto3" json:"failureReason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwapFailure) Reset()         { *m = SwapFailure{} }
func (m *SwapFailure) String() string { return proto.CompactTextString(m) }
func (*SwapFailure) ProtoMessage()    {}
func (*SwapFailure) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d3c6379d5206233, []int{19}
}

func (m *SwapFailure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwapFailure.Unmarshal(m, b)
}
func (m *SwapFailure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwapFailure.Marshal(b, m, deterministic)
}
func (m *SwapFailure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapFailure.Merge(m, src)
}
func (m *SwapFailure) XXX_Size() int {
	return xxx_messageInfo_SwapFailure.Size(m)
}
func (m *SwapFailure) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapFailure.DiscardUnknown(m)
}

var xxx_messageInfo_SwapFailure proto.InternalMessageInfo

func (m *SwapFailure) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *SwapFailure) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *SwapFailure) GetFunds() *BigInteger {
	if m != nil {
		return m.Funds
	}
	return nil
}

func (m *SwapFailure) GetFailureReason() string {
	if m != nil {
		return m.FailureReason
	}
	return ""
}

func init() {
	proto.RegisterEnum("lssdrpc.OrderSide", OrderSide_name, OrderSide_value)
	proto.RegisterEnum("lssdrpc.SwapSuccess_Role", SwapSuccess_Role_name, SwapSuccess_Role_value)
	proto.RegisterType((*BigInteger)(nil), "lssdrpc.BigInteger")
	proto.RegisterType((*AddCurrencyRequest)(nil), "lssdrpc.AddCurrencyRequest")
	proto.RegisterType((*AddCurrencyResponse)(nil), "lssdrpc.AddCurrencyResponse")
	proto.RegisterType((*EnableTradingPairRequest)(nil), "lssdrpc.EnableTradingPairRequest")
	proto.RegisterType((*EnableTradingPairResponse)(nil), "lssdrpc.EnableTradingPairResponse")
	proto.RegisterType((*ListOrdersRequest)(nil), "lssdrpc.ListOrdersRequest")
	proto.RegisterType((*ListOrdersResponse)(nil), "lssdrpc.ListOrdersResponse")
	proto.RegisterType((*PlaceOrderRequest)(nil), "lssdrpc.PlaceOrderRequest")
	proto.RegisterType((*PlaceOrderResponse)(nil), "lssdrpc.PlaceOrderResponse")
	proto.RegisterType((*OrderbookFailure)(nil), "lssdrpc.OrderbookFailure")
	proto.RegisterType((*PlaceOrderFailure)(nil), "lssdrpc.PlaceOrderFailure")
	proto.RegisterType((*CancelOrderRequest)(nil), "lssdrpc.CancelOrderRequest")
	proto.RegisterType((*CancelOrderResponse)(nil), "lssdrpc.CancelOrderResponse")
	proto.RegisterType((*SubscribeOrdersRequest)(nil), "lssdrpc.SubscribeOrdersRequest")
	proto.RegisterType((*OrderUpdate)(nil), "lssdrpc.OrderUpdate")
	proto.RegisterType((*Order)(nil), "lssdrpc.Order")
	proto.RegisterType((*SubscribeSwapsRequest)(nil), "lssdrpc.SubscribeSwapsRequest")
	proto.RegisterType((*SwapResult)(nil), "lssdrpc.SwapResult")
	proto.RegisterType((*SwapSuccess)(nil), "lssdrpc.SwapSuccess")
	proto.RegisterType((*SwapFailure)(nil), "lssdrpc.SwapFailure")
}

func init() { proto.RegisterFile("protobuf/lssdrpc.proto", fileDescriptor_1d3c6379d5206233) }

var fileDescriptor_1d3c6379d5206233 = []byte{
	// 1059 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x57, 0xcd, 0x6f, 0xdc, 0x44,
	0x14, 0xaf, 0xb3, 0xdf, 0xcf, 0xc9, 0x36, 0x9d, 0xa4, 0xc1, 0xdd, 0x44, 0xa1, 0x8c, 0x50, 0x55,
	0x2a, 0x11, 0xa2, 0x2d, 0x20, 0x24, 0xb8, 0x24, 0x51, 0x42, 0xca, 0x87, 0xba, 0xf2, 0x16, 0x0e,
	0xdc, 0xbc, 0xf6, 0x24, 0x31, 0xf5, 0xda, 0xcb, 0x8c, 0xdd, 0x28, 0x47, 0xfe, 0x03, 0x2e, 0x9c,
	0x39, 0x23, 0x71, 0xe2, 0xc6, 0x7f, 0xc2, 0x3f, 0xc2, 0x9d, 0xf9, 0xb2, 0x3d, 0x8e, 0xbd, 0xd9,
	0x72, 0xe0, 0xb6, 0xf3, 0xde, 0x6f, 0x9e, 0xdf, 0xfb, 0xbd, 0xaf, 0x59, 0xd8, 0x59, 0xd0, 0x24,
	0x4d, 0x66, 0xd9, 0xc5, 0x47, 0x11, 0x63, 0x01, 0x5d, 0xf8, 0x07, 0x52, 0x80, 0x7a, 0xfa, 0x88,
	0x31, 0xc0, 0x71, 0x78, 0xf9, 0x22, 0x4e, 0xc9, 0x25, 0xa1, 0x68, 0x1b, 0x3a, 0x6f, 0xbc, 0x28,
	0x23, 0x8e, 0xf5, 0xd8, 0x7a, 0x3a, 0x70, 0xd5, 0x01, 0xff, 0x6a, 0x01, 0x3a, 0x0a, 0x82, 0x93,
	0x8c, 0x52, 0x12, 0xfb, 0x37, 0x2e, 0xf9, 0x29, 0x23, 0x2c, 0x45, 0x23, 0xe8, 0xfb, 0x5a, 0xa4,
	0xf1, 0xc5, 0x19, 0xed, 0x03, 0x44, 0x71, 0x70, 0x72, 0xe5, 0xc5, 0x31, 0x89, 0x9c, 0x35, 0xa9,
	0x35, 0x24, 0x68, 0x8f, 0xdf, 0x25, 0x34, 0x9d, 0x78, 0xe9, 0x95, 0xd3, 0x12, 0xda, 0xf3, 0x7b,
	0x6e, 0x21, 0xe1, 0x96, 0x7b, 0xd4, 0xbb, 0x3e, 0xe1, 0x47, 0xa7, 0xad, 0x95, 0xb9, 0xe0, 0x78,
	0x00, 0xbd, 0x34, 0x62, 0xe2, 0x27, 0x7e, 0x08, 0x5b, 0x15, 0xb7, 0xd8, 0x22, 0x89, 0x19, 0xc1,
	0x63, 0x70, 0x4e, 0x63, 0x6f, 0x16, 0x91, 0x57, 0xd4, 0x0b, 0xc2, 0xf8, 0x72, 0xe2, 0x85, 0x34,
	0xf7, 0x79, 0x07, 0xba, 0x0b, 0x7e, 0x7c, 0x11, 0x68, 0x8f, 0xf5, 0x09, 0xef, 0xc2, 0xa3, 0x86,
	0x3b, 0xda, 0xe0, 0xcf, 0x16, 0x3c, 0xf8, 0x26, 0x64, 0xe9, 0x4b, 0x1a, 0x10, 0xca, 0x56, 0x98,
	0x42, 0xcf, 0x60, 0x33, 0x8c, 0xfd, 0x28, 0x0b, 0xc8, 0xcb, 0xeb, 0x58, 0x5d, 0x91, 0x04, 0xf4,
	0xdd, 0x9a, 0x1c, 0x21, 0x68, 0xb3, 0xd7, 0xe1, 0x42, 0x52, 0xb0, 0xe1, 0xca, 0xdf, 0x22, 0x07,
	0x51, 0x38, 0x0f, 0x55, 0xe8, 0x1b, 0xae, 0x3a, 0xe0, 0x2f, 0x00, 0x99, 0x2e, 0x28, 0xcf, 0xd0,
	0x13, 0xe8, 0x26, 0xea, 0x0b, 0xd6, 0xe3, 0xd6, 0x53, 0x7b, 0x3c, 0x3c, 0xc8, 0xd3, 0x2c, 0x81,
	0xae, 0xd6, 0xe2, 0xdf, 0x79, 0x04, 0x93, 0xc8, 0xf3, 0x89, 0x12, 0xaf, 0x88, 0xe0, 0x09, 0xf7,
	0x2a, 0x0c, 0x88, 0xf4, 0x7a, 0x38, 0x46, 0x55, 0x9b, 0x53, 0xae, 0x71, 0xa5, 0x1e, 0x7d, 0x00,
	0x9d, 0x8b, 0x2c, 0x0e, 0x98, 0x74, 0xdf, 0x1e, 0x6f, 0x15, 0xc0, 0xb2, 0xa2, 0x5c, 0x85, 0x10,
	0xd0, 0x05, 0x0d, 0x7d, 0x22, 0x83, 0x5a, 0x06, 0x95, 0x08, 0xfc, 0x17, 0xaf, 0x36, 0xd3, 0x57,
	0x1d, 0xea, 0x67, 0x60, 0xb3, 0x6b, 0x6f, 0x31, 0xcd, 0x7c, 0x9f, 0x30, 0x26, 0x3d, 0xb6, 0xc7,
	0xdb, 0x85, 0x9d, 0x69, 0xa9, 0xe3, 0xd5, 0x62, 0x42, 0x79, 0x38, 0x1d, 0x49, 0x83, 0x8c, 0xa7,
	0xc6, 0x11, 0x47, 0x2b, 0x35, 0xfa, 0x14, 0x7a, 0x17, 0x5e, 0x18, 0x65, 0x94, 0xe8, 0x80, 0x46,
	0x05, 0xb2, 0xf4, 0xe7, 0x4c, 0x21, 0x44, 0x45, 0x6a, 0xb0, 0xa8, 0xc8, 0x24, 0x4b, 0xfd, 0x64,
	0x4e, 0xf0, 0x9f, 0x16, 0x6c, 0x4a, 0xd8, 0x2c, 0x49, 0x5e, 0x6b, 0xe8, 0x52, 0x9a, 0x0b, 0xfa,
	0xd6, 0x56, 0xd2, 0xf7, 0x3e, 0x6c, 0xe8, 0xaf, 0xb9, 0xc4, 0x63, 0x49, 0xac, 0x7a, 0xc6, 0xad,
	0x0a, 0xd1, 0x27, 0x60, 0x53, 0x9e, 0xda, 0x90, 0x92, 0xe0, 0x8c, 0xdc, 0x49, 0xb5, 0x89, 0xc3,
	0xbf, 0x55, 0x8a, 0x23, 0xf7, 0x5a, 0xf3, 0xad, 0x8f, 0x8d, 0x7c, 0x97, 0x5c, 0x98, 0x50, 0x74,
	0x0a, 0xf7, 0x93, 0x92, 0x03, 0x79, 0x5b, 0x45, 0xf8, 0xa8, 0xca, 0xbc, 0xc1, 0x11, 0x37, 0x71,
	0xfb, 0x8e, 0xa0, 0x55, 0x87, 0x87, 0xcf, 0x00, 0x9d, 0x78, 0xb1, 0x4f, 0xa2, 0xb7, 0x2a, 0x5f,
	0x87, 0xe7, 0x43, 0xe0, 0xb8, 0x42, 0x0d, 0x9e, 0xfc, 0x28, 0x06, 0x46, 0xc5, 0x8e, 0xee, 0x6f,
	0x07, 0x76, 0xa6, 0xd9, 0x8c, 0xf9, 0x34, 0x9c, 0x91, 0x4a, 0x8f, 0xe3, 0x0c, 0x6c, 0x29, 0xf8,
	0x6e, 0x11, 0x78, 0x29, 0x29, 0x2b, 0xc9, 0xba, 0xbb, 0x92, 0x3e, 0x86, 0xf5, 0x44, 0x7d, 0x61,
	0x9e, 0xf0, 0x11, 0xba, 0xb4, 0xf0, 0x2a, 0xa8, 0xe3, 0x3e, 0x74, 0x33, 0xf9, 0x1d, 0xfc, 0x8f,
	0x05, 0x1d, 0x89, 0xf9, 0xef, 0x31, 0x96, 0x9d, 0xd6, 0x5a, 0xd5, 0x69, 0x65, 0x01, 0xb6, 0x57,
	0x16, 0xe0, 0x1e, 0x0c, 0x7c, 0x4a, 0xb8, 0x6f, 0xc1, 0x51, 0xea, 0x74, 0x38, 0xbc, 0xed, 0x96,
	0x82, 0x62, 0x60, 0x74, 0x57, 0x0c, 0x0c, 0xbe, 0x15, 0x42, 0x96, 0x4f, 0x3f, 0xa7, 0x27, 0x87,
	0xa2, 0x21, 0xc1, 0xef, 0xc0, 0xc3, 0x22, 0x11, 0xa2, 0xc0, 0x8a, 0x3c, 0xdc, 0x00, 0x88, 0x33,
	0xcf, 0x58, 0x16, 0xa5, 0xe8, 0x10, 0x7a, 0xec, 0xad, 0xc6, 0x40, 0x0e, 0x13, 0x37, 0xf2, 0xd6,
	0x5e, 0xbb, 0xb3, 0x90, 0x8b, 0xa6, 0xee, 0xe9, 0x4d, 0x88, 0xff, 0x6e, 0x81, 0x6d, 0x58, 0x35,
	0x99, 0xb7, 0xaa, 0xcc, 0x97, 0xb9, 0x5a, 0x6b, 0xee, 0xf3, 0xd5, 0x63, 0x92, 0xcf, 0x7e, 0x7a,
	0xee, 0xb1, 0x2b, 0xb5, 0xf6, 0x5c, 0x75, 0x40, 0x9f, 0xc3, 0xd0, 0x9b, 0x27, 0x59, 0x9c, 0xba,
	0xc4, 0x27, 0xe1, 0x1b, 0x12, 0xc8, 0x0c, 0x2c, 0xb1, 0x74, 0x0b, 0x8a, 0x9e, 0x03, 0x28, 0xc9,
	0x94, 0xc4, 0xa9, 0xcc, 0xd0, 0x92, 0x8b, 0x06, 0x0c, 0x7d, 0x08, 0x6d, 0x9a, 0x44, 0x44, 0xa6,
	0x68, 0x68, 0xf4, 0xad, 0x41, 0xc4, 0x81, 0xcb, 0x01, 0xae, 0x84, 0x89, 0x95, 0xe7, 0x17, 0x5b,
	0x58, 0xbb, 0xd8, 0x97, 0x11, 0xd4, 0xe4, 0x08, 0xc3, 0x7a, 0x2e, 0x93, 0x1e, 0x0d, 0x24, 0xae,
	0x22, 0x13, 0xd5, 0x46, 0x27, 0x94, 0x84, 0x73, 0xef, 0x92, 0x38, 0x20, 0x01, 0xa5, 0xa0, 0xac,
	0x70, 0x7b, 0xe5, 0x2e, 0xd9, 0x83, 0xb6, 0x70, 0x13, 0x0d, 0xa0, 0xf3, 0xea, 0xe8, 0xeb, 0x53,
	0x77, 0xf3, 0x9e, 0xf8, 0xf9, 0xad, 0xfc, 0x69, 0xe1, 0x5f, 0x2c, 0x95, 0xda, 0x7c, 0x70, 0xfd,
	0xaf, 0xa9, 0xad, 0x8d, 0xf0, 0x76, 0xc3, 0x08, 0x7f, 0xb6, 0x0f, 0x83, 0xa2, 0x69, 0x50, 0x0f,
	0x5a, 0xb3, 0xec, 0x86, 0xfb, 0xdc, 0xe7, 0xfd, 0x45, 0xa2, 0x68, 0xd3, 0x1a, 0x7f, 0x0f, 0xa0,
	0x99, 0x0a, 0x09, 0x43, 0xe7, 0x60, 0x1b, 0x0f, 0x20, 0xb4, 0x5b, 0x7c, 0xbe, 0xfe, 0x5a, 0x1b,
	0xed, 0x35, 0x2b, 0xd5, 0x08, 0x1c, 0xff, 0x08, 0xeb, 0x69, 0xf9, 0xf2, 0x61, 0xe8, 0x07, 0x78,
	0x50, 0x7b, 0x0f, 0xa1, 0xf7, 0x0a, 0x13, 0xcb, 0xde, 0x57, 0x23, 0x7c, 0x17, 0x44, 0x7f, 0xeb,
	0x8f, 0xb5, 0xfc, 0xd5, 0xc2, 0x57, 0x05, 0x94, 0x9b, 0x07, 0x35, 0xed, 0xdb, 0xdc, 0xf0, 0x6e,
	0xa3, 0x4e, 0xbf, 0x0d, 0x38, 0x0f, 0xc6, 0x5c, 0x37, 0x78, 0xa8, 0x6f, 0x0d, 0x83, 0x87, 0x86,
	0x55, 0x80, 0xbe, 0x82, 0xfb, 0xb7, 0x56, 0x01, 0x7a, 0xb7, 0xac, 0xfe, 0xc6, 0x25, 0x31, 0xda,
	0xae, 0xce, 0x3b, 0xb5, 0x2b, 0x0e, 0x2d, 0x11, 0x5c, 0xf9, 0x64, 0x33, 0x82, 0xab, 0x3d, 0x25,
	0x8d, 0xe0, 0xea, 0x6f, 0xbc, 0xf1, 0x04, 0x3a, 0x62, 0xbb, 0x32, 0xf4, 0x25, 0x0c, 0xab, 0xd3,
	0x11, 0xed, 0xd7, 0x5d, 0x33, 0xc7, 0xe6, 0x68, 0xab, 0xd2, 0xb8, 0x6a, 0x7a, 0x1e, 0x5a, 0xb3,
	0xae, 0xfc, 0x0f, 0xf0, 0xfc, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xc5, 0xa0, 0xa3, 0x1d,
	0x0c, 0x00, 0x00,
}
